dist: xenial
language: python
python:
  - 2.7

before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y libmapnik-dev mapnik-utils python-mapnik
  - virtualenv --system-site-packages venv
  - source venv/bin/activate
  - pip install -r requirements.txt
install:
  - python setup.py develop
before_script:
  - pip install nose
  - pip install coverage
script:
  - nosetests --with-coverage --cover-package=landez
after_success:
  - pip install coveralls
  - coveralls
