dist: trusty
sudo: required
language: python
python:
  - 3.5

before_install:
  - deactivate
  - sudo apt-get install python3-mapnik
  - virtualenv --system-site-packages venv -p python3
  - source venv/bin/activate
  - pip install -r requirements.txt
install:
  - python setup.py develop
before_script:
  - pip install nose
  - pip install coverage
script:
  - nosetests --with-coverage --cover-package=landez
after_success:
  - pip install coveralls
  - coveralls
